// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	email "exporter/internal/handler/email"
	monitor "exporter/internal/handler/monitor"
	refresh "exporter/internal/handler/refresh"
	"exporter/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/postemail",
				Handler: email.PostemailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/easyemail",
				Handler: email.EasyemailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/email"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/refresh",
				Handler: refresh.RefreshHandler(serverCtx),
			},
		},
		rest.WithPrefix("/refresh"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/encrypt",
				Handler: monitor.EncryptHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/report",
				Handler: monitor.ReportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/monitor"),
	)
}
